export const RESOURCE_DEFS = {
  organizations: {
    title: "Organizations",
    path: "/organization",
    listKey: "organizations",
    singleKey: "organization",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["active", "Active", "checkbox"],
    ],
    tableColumns: ["name", "active", "description"],
  },
  workgroups: {
    title: "Spaces",
    path: "/space",
    listKey: "workgroups",
    singleKey: "workgroup",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["organizationId", "Organization", "organization-combobox"],
      ["categoryId", "Category", "category-combobox"],
      ["listType", "List Type", "number"],
    ],
    tableColumns: ["name", "organizationId", "categoryId", "listType"],
  },
  groups: {
    title: "Circles",
    path: "/circle",
    listKey: "groups",
    singleKey: "group",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category", "category-combobox"],
      ["listType", "List Type", "number"],
    ],
    tableColumns: ["name", "categoryId", "listType"],
  },
  users: {
    title: "People",
    path: "/person",
    listKey: "users",
    singleKey: "user",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["firstName", "First Name", "text"],
      ["lastName", "Last Name", "text"],
      ["alias", "Alias", "text"],
      ["email", "Email", "text"],
      ["organizationId", "Organization", "organization-combobox"],
      ["active", "Active", "checkbox"],
      ["verified", "Verified", "checkbox"],
      ["systemAdmin", "System Admin", "checkbox"],
      ["organizationAdmin", "Organization Admin", "checkbox"],
      ["workgroupAdmin", "Space Admin", "checkbox"],
      ["adminWorkgroupId", "Admin Space", "workgroup-combobox"],
    ],
    tableColumns: ["firstName", "lastName", "email", "active", "verified", "systemAdmin", "organizationAdmin", "workgroupAdmin"],
    savedViews: [
      { id: "active", name: "Active", filters: { active: "true" }, columns: ["firstName", "lastName", "email", "verified"] },
      { id: "unverified", name: "Unverified", filters: { active: "true", verified: "false" }, columns: ["firstName", "lastName", "email", "active"] },
      { id: "admins", name: "Admins", filters: { adminRole: "organizationAdmin" }, columns: ["firstName", "lastName", "email", "organizationAdmin", "workgroupAdmin"] },
      { id: "disabled", name: "Disabled", filters: { active: "false" }, columns: ["firstName", "lastName", "email", "verified"] },
      { id: "space-admins", name: "Space Admins", filters: { adminRole: "workgroupAdmin" }, columns: ["firstName", "lastName", "email", "adminWorkgroupId"] },
    ],
  },
  roles: {
    title: "Roles",
    path: "/role",
    listKey: "roles",
    singleKey: "role",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
    ],
    tableColumns: ["name", "description", "protected"],
    savedViews: [
      { id: "protected", name: "Protected", columns: ["name", "protected", "description"] },
      { id: "custom", name: "Custom", columns: ["name", "description", "protected"] },
    ],
  },
  capabilities: {
    title: "Capabilities",
    path: "/capability",
    listKey: "capabilities",
    singleKey: "capability",
    idField: "id",
    fields: [["name", "Name", "text"]],
    tableColumns: ["name"],
  },
  categories: {
    title: "Categories",
    path: "/category",
    listKey: "categories",
    singleKey: "category",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["creator", "Owner Person", "user-combobox"],
    ],
    tableColumns: ["name", "creator", "description"],
  },
  items: {
    title: "Items",
    path: "/item",
    listKey: "items",
    singleKey: "item",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["url", "URL", "text"],
      ["location", "Location", "text"],
      ["categoryId", "Category", "category-combobox"],
      ["imageId", "Picture", "image-combobox"],
    ],
    tableColumns: ["name", "workgroupId", "categoryId", "url", "location"],
  },
  images: {
    title: "Pictures",
    path: "/picture",
    listKey: "images",
    singleKey: "image",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category", "category-combobox"],
    ],
    tableColumns: ["name", "workgroupId", "categoryId", "description"],
  },
  lists: {
    title: "Lists",
    path: "/list",
    listKey: "lists",
    singleKey: "list",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category", "category-combobox"],
    ],
    tableColumns: ["name", "workgroupId", "categoryId", "description"],
  },
  elections: {
    title: "Polls",
    path: "/poll",
    listKey: "elections",
    singleKey: "election",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["listId", "List", "list-combobox"],
      ["groupId", "Circle", "group-combobox"],
      ["categoryId", "Category", "category-combobox"],
      ["imageId", "Picture", "image-combobox"],
      ["electionType", "Poll Type", "number"],
      ["expiration", "Expiration (ISO)", "text"],
    ],
    tableColumns: ["name", "workgroupId", "expiration", "publicAccessMode", "abuseStatus", "electionType"],
    savedViews: [
      { id: "active", name: "Active", filters: { pollStatus: "active" }, columns: ["name", "workgroupId", "expiration", "publicAccessMode"] },
      { id: "expired", name: "Expired", filters: { pollStatus: "expired" }, columns: ["name", "workgroupId", "expiration", "abuseStatus"] },
      { id: "public", name: "Public", filters: { publicStatus: "public" }, columns: ["name", "workgroupId", "publicAccessMode", "abuseStatus"] },
      { id: "reported", name: "Reported", filters: { abuseStatus: "reported" }, columns: ["name", "workgroupId", "abuseStatus", "publicAccessMode"] },
      { id: "recent", name: "Recently Created", columns: ["name", "workgroupId", "expiration", "electionType"] },
    ],
  },
  votes: {
    title: "Votes",
    path: "/vote",
    listKey: "votes",
    singleKey: "vote",
    idField: "id",
    deletable: false,
    fields: [
      ["electionId", "Poll", "election-combobox"],
      ["itemId", "Item", "item-combobox"],
      ["userId", "Person", "user-combobox"],
      ["statusId", "Status ID", "number"],
    ],
    tableColumns: ["electionId", "itemId", "userId", "statusId"],
  },
  notifications: {
    title: "Notifications",
    path: "/notification",
    listKey: "notifications",
    singleKey: "notification",
    idField: "id",
    fields: [
      ["userId", "Person", "user-combobox"],
      ["senderId", "Sender", "user-combobox"],
      ["text", "Text", "textarea"],
      ["type", "Type", "text"],
      ["objectId", "Object ID", "text"],
      ["statusId", "Status ID", "number"],
    ],
    tableColumns: ["type", "userId", "statusId", "objectId", "text"],
    savedViews: [
      { id: "unread", name: "Unread", filter: "unread", columns: ["type", "userId", "statusId", "text"] },
      { id: "failed-delivery", name: "Failed Delivery", filter: "failed", columns: ["type", "userId", "statusId", "text"] },
      { id: "recent-system", name: "Recent System", filter: "system", columns: ["type", "userId", "objectId", "text"] },
    ],
  },
  preferences: {
    title: "Preferences",
    path: "/preference",
    listKey: "preferences",
    singleKey: "preference",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["value", "Value", "textarea"],
    ],
    tableColumns: ["name", "value"],
  },
};
