export const RESOURCE_DEFS = {
  organizations: {
    title: "Organizations",
    path: "/organization",
    listKey: "organizations",
    singleKey: "organization",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["active", "Active", "checkbox"],
    ],
  },
  workgroups: {
    title: "Spaces",
    path: "/space",
    listKey: "workgroups",
    singleKey: "workgroup",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["organizationId", "Organization", "organization-combobox"],
      ["categoryId", "Category", "category-combobox"],
      ["listType", "List Type", "number"],
    ],
  },
  groups: {
    title: "Circles",
    path: "/circle",
    listKey: "groups",
    singleKey: "group",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category", "category-combobox"],
      ["listType", "List Type", "number"],
    ],
  },
  users: {
    title: "People",
    path: "/person",
    listKey: "users",
    singleKey: "user",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["firstName", "First Name", "text"],
      ["lastName", "Last Name", "text"],
      ["alias", "Alias", "text"],
      ["email", "Email", "text"],
      ["organizationId", "Organization", "organization-combobox"],
      ["active", "Active", "checkbox"],
      ["verified", "Verified", "checkbox"],
      ["systemAdmin", "System Admin", "checkbox"],
      ["organizationAdmin", "Organization Admin", "checkbox"],
      ["workgroupAdmin", "Space Admin", "checkbox"],
      ["adminWorkgroupId", "Admin Space", "workgroup-combobox"],
    ],
  },
  roles: {
    title: "Roles",
    path: "/role",
    listKey: "roles",
    singleKey: "role",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
    ],
  },
  capabilities: {
    title: "Capabilities",
    path: "/capability",
    listKey: "capabilities",
    singleKey: "capability",
    idField: "id",
    fields: [["name", "Name", "text"]],
  },
  categories: {
    title: "Categories",
    path: "/category",
    listKey: "categories",
    singleKey: "category",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["creator", "Owner Person", "user-combobox"],
    ],
  },
  items: {
    title: "Items",
    path: "/item",
    listKey: "items",
    singleKey: "item",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["url", "URL", "text"],
      ["location", "Location", "text"],
      ["categoryId", "Category", "category-combobox"],
      ["imageId", "Picture", "image-combobox"],
    ],
  },
  images: {
    title: "Pictures",
    path: "/picture",
    listKey: "images",
    singleKey: "image",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category", "category-combobox"],
    ],
  },
  lists: {
    title: "Lists",
    path: "/list",
    listKey: "lists",
    singleKey: "list",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category", "category-combobox"],
    ],
  },
  elections: {
    title: "Polls",
    path: "/poll",
    listKey: "elections",
    singleKey: "election",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Space", "workgroup-combobox"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["listId", "List", "list-combobox"],
      ["groupId", "Circle", "group-combobox"],
      ["categoryId", "Category", "category-combobox"],
      ["imageId", "Picture", "image-combobox"],
      ["electionType", "Poll Type", "number"],
      ["expiration", "Expiration (ISO)", "text"],
    ],
  },
  votes: {
    title: "Votes",
    path: "/vote",
    listKey: "votes",
    singleKey: "vote",
    idField: "id",
    deletable: false,
    fields: [
      ["electionId", "Poll", "election-combobox"],
      ["itemId", "Item", "item-combobox"],
      ["userId", "Person", "user-combobox"],
      ["statusId", "Status ID", "number"],
    ],
  },
  notifications: {
    title: "Notifications",
    path: "/notification",
    listKey: "notifications",
    singleKey: "notification",
    idField: "id",
    fields: [
      ["userId", "Person", "user-combobox"],
      ["senderId", "Sender", "user-combobox"],
      ["text", "Text", "textarea"],
      ["type", "Type", "text"],
      ["objectId", "Object ID", "text"],
      ["statusId", "Status ID", "number"],
    ],
  },
  preferences: {
    title: "Preferences",
    path: "/preference",
    listKey: "preferences",
    singleKey: "preference",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["value", "Value", "textarea"],
    ],
  },
};
