export const RESOURCE_DEFS = {
  organizations: {
    title: "Organizations",
    path: "/organization",
    listKey: "organizations",
    singleKey: "organization",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["active", "Active", "checkbox"],
    ],
  },
  workgroups: {
    title: "Workgroups",
    path: "/workgroup",
    listKey: "workgroups",
    singleKey: "workgroup",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["organizationId", "Organization ID", "text"],
      ["categoryId", "Category ID", "text"],
      ["listType", "List Type", "number"],
    ],
  },
  groups: {
    title: "Groups",
    path: "/group",
    listKey: "groups",
    singleKey: "group",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category ID", "text"],
      ["listType", "List Type", "number"],
    ],
  },
  users: {
    title: "Users",
    path: "/user",
    listKey: "users",
    singleKey: "user",
    idField: "id",
    fields: [
      ["firstName", "First Name", "text"],
      ["lastName", "Last Name", "text"],
      ["alias", "Alias", "text"],
      ["email", "Email", "text"],
      ["organizationId", "Organization ID", "text"],
      ["active", "Active", "checkbox"],
      ["verified", "Verified", "checkbox"],
      ["systemAdmin", "System Admin", "checkbox"],
      ["organizationAdmin", "Organization Admin", "checkbox"],
      ["workgroupAdmin", "Workgroup Admin", "checkbox"],
      ["adminWorkgroupId", "Admin Workgroup ID", "text"],
    ],
  },
  roles: {
    title: "Roles",
    path: "/role",
    listKey: "roles",
    singleKey: "role",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
    ],
  },
  capabilities: {
    title: "Capabilities",
    path: "/capability",
    listKey: "capabilities",
    singleKey: "capability",
    idField: "id",
    fields: [["name", "Name", "text"]],
  },
  categories: {
    title: "Categories",
    path: "/category",
    listKey: "categories",
    singleKey: "category",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
    ],
  },
  items: {
    title: "Items",
    path: "/item",
    listKey: "items",
    singleKey: "item",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Workgroup ID", "text"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["url", "URL", "text"],
      ["location", "Location", "text"],
      ["categoryId", "Category ID", "text"],
      ["imageId", "Image ID", "text"],
    ],
  },
  images: {
    title: "Images",
    path: "/image",
    listKey: "images",
    singleKey: "image",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Workgroup ID", "text"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category ID", "text"],
    ],
  },
  lists: {
    title: "Lists",
    path: "/list",
    listKey: "lists",
    singleKey: "list",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Workgroup ID", "text"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["categoryId", "Category ID", "text"],
    ],
  },
  elections: {
    title: "Elections",
    path: "/election",
    listKey: "elections",
    singleKey: "election",
    idField: "id",
    supportsWorkgroupScope: true,
    fields: [
      ["workgroupId", "Workgroup ID", "text"],
      ["name", "Name", "text"],
      ["description", "Description", "textarea"],
      ["listId", "List ID", "text"],
      ["groupId", "Audience Group ID", "text"],
      ["categoryId", "Category ID", "text"],
      ["imageId", "Image ID", "text"],
      ["electionType", "Election Type", "number"],
      ["expiration", "Expiration (ISO)", "text"],
    ],
  },
  votes: {
    title: "Votes",
    path: "/vote",
    listKey: "votes",
    singleKey: "vote",
    idField: "id",
    deletable: false,
    fields: [
      ["electionId", "Election ID", "text"],
      ["itemId", "Item ID", "text"],
      ["userId", "User ID", "text"],
      ["statusId", "Status ID", "number"],
    ],
  },
  notifications: {
    title: "Notifications",
    path: "/notification",
    listKey: "notifications",
    singleKey: "notification",
    idField: "id",
    fields: [
      ["userId", "User ID", "text"],
      ["senderId", "Sender ID", "text"],
      ["text", "Text", "textarea"],
      ["type", "Type", "text"],
      ["objectId", "Object ID", "text"],
      ["statusId", "Status ID", "number"],
    ],
  },
  preferences: {
    title: "Preferences",
    path: "/preference",
    listKey: "preferences",
    singleKey: "preference",
    idField: "id",
    fields: [
      ["name", "Name", "text"],
      ["value", "Value", "textarea"],
    ],
  },
};
